name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # As long as the dependencies are not updated
    # Fixes: AttributeError: module 'asyncio.coroutines' has no attribute '_DEBUG'
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Run build
      run: make build

    - name: Run test
      run: make test

    - name: Store test results
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: target/*.xml
